sudo: required

services:
  - docker

install:
  - curl -sSf https://nim-lang.org/choosenim/init.sh | sh -s -- -y
  - export PATH=~/.nimble/bin:$PATH

script:
  - nim c build

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  skip_cleanup: true
  script: ./build $TRAVIS_TAG
  on:
    tags: true
