sudo: required

services:
  - docker

branches:
  only:
  - master

before_script:
  - chmod +x build

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./build
