sudo: required

services:
  - docker

before_script:
  - docker build -t nimlang/nim:0.11.0-slim 0.11.0/slim
  - docker build -t nimlang/nim:0.11.2-slim 0.11.2/slim
  - docker build -t nimlang/nim:0.12.0-slim 0.12.0/slim
  - docker build -t nimlang/nim:0.13.0-slim 0.13.0/slim
  - docker build -t nimlang/nim:0.14.0-slim 0.14.0/slim
  - docker build -t nimlang/nim:0.14.2-slim 0.14.2/slim
  - docker build -t nimlang/nim:0.14.3-slim 0.14.3/slim
  - docker build -t nimlang/nim:0.13.0 0.13.0
  - docker build -t nimlang/nim:0.14.0 0.14.0
  - docker build -t nimlang/nim:0.14.2 -t nimlang/nim:latest 0.14.2
  - docker build -t nimlang/nim:0.14.3 -t nimlang/nim:devel 0.14.3
  - docker build -t nimlang/nim:0.13.0-onbuild 0.13.0/onbuild
  - docker build -t nimlang/nim:0.14.0-onbuild 0.14.0/onbuild
  - docker build -t nimlang/nim:0.14.2-onbuild 0.14.2/onbuild
  - docker build -t nimlang/nim:0.14.3-onbuild 0.14.3/onbuild

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push nimlang/nim:0.11.0-slim
  - docker push nimlang/nim:0.11.2-slim
  - docker push nimlang/nim:0.12.0-slim
  - docker push nimlang/nim:0.13.0-slim
  - docker push nimlang/nim:0.14.0-slim
  - docker push nimlang/nim:0.14.2-slim
  - docker push nimlang/nim:0.14.3-slim
  - docker push nimlang/nim:0.13.0
  - docker push nimlang/nim:0.14.0
  - docker push nimlang/nim:0.14.2
  - docker push nimlang/nim:0.14.3
  - docker push nimlang/nim:latest
  - docker push nimlang/nim:devel
  - docker push nimlang/nim:0.13.0-onbuild
  - docker push nimlang/nim:0.14.0-onbuild
  - docker push nimlang/nim:0.14.2-onbuild
  - docker push nimlang/nim:0.14.3-onbuild