sudo: required

services:
  - docker

branches:
  only:
  - master

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run --rm -v `pwd`:/usr/src/app -w /usr/src/app nimlang/nim build.nim
  - ./build
